### ISSUE TITLE
Decimate incorrect for nondivisible factors

### ISSUE THREAD

**Issue by psambit9791** [psambit9791/jDSP#1]
Problems occurring for values of factors for which the sampling frequency is not divisible by the factor. Array length is less by 1.

OUTPUT:

array lengths differed, expected.length=32 actual.length=31; arrays first differed at element [31]; 
Expected :-0.494
Actual   :end of array

at com.onyx.jdsp.TestDecimate.DecimateWithZeroPhaseTest(TestDecimate.java:102)
Caused by: java.lang.AssertionError: expected:<-0.494> but was:<end of array>
at org.junit.Assert.failNotEquals(Assert.java:835)

**Comment by psambit9791** [comment]
Resolved by changing the length of the output array in Decimate class.
