### ISSUE TITLE
Error in forked process when trying to compile project using JDSP

### ISSUE THREAD

**Issue by LobsterMan123** [psambit9791/jDSP#88]
I am trying to use JDSP (the newest version) and when I try to compile in Maven, I get an unusual error as seen below:

`[ERROR] There was an error in the forked process
[ERROR] org/apache/maven/surefire/report/RunModeSetter                        [ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process                                              [ERROR] org/apache/maven/surefire/report/RunModeSetter
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:628)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:285)                                                      [ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:250)`

There are at least 30 additional such ERROR tags.  If I'm not mistaken this type of error deals with compatibility issues between a library and the Java installation.  I used the most up-to-date surefire plugin and still got the same "forked" error.  I went ahead and tried to compile an earlier project that used JDSP (albeit an older version of JDSP invoked in that project's pom file), which did compile and worked nicely back when I wrote that program, yet this time, I got the same "forked" error.  I know it's not my Java installation as I compiled another project that doesn't use JDSP at all and that project compiled fine.

_1) Do users need to have some special version of Java installed in order to use JDSP from now on (I'm using Java 17 and cannot update to a higher version)?_

_2) Am I trying to import the JDSP library at an inconvenient time (December 8, 2024 at around 2:36 AM EST)?_

I believe my old JDSP project's pom file was invoking the old version of JDSP already downloaded and located in my .m2 folder/on-board repository yet it still yielded that error which never happened before, so I don't see why Maven Central would even need to be invoked for some potentially new/different version of JDSP for my old program using something already installed (admittedly, I stepped away during the old project's compilation, so I didn't see if JDSP - even from the old project - was being re-downloaded from Maven or not).

I'd be happy to share my pom file just in case if you would like to see if I have any dependencies or plugins that might be interfering with JDSP.  Thanks and I hope that JDSP can continue to be used on any architecture and with a flexibility of Java versions as it's done in the past.

**Comment by psambit9791** [comment]
@LobsterMan123 
Sorry for the very late response.
is this still an issue?

**Comment by LiveNathan** [comment]
I'm experiencing the exact same issue with a slightly different environment:

**My setup:**
- Java 24
- Maven Surefire Plugin 3.5.3  
- jDSP 3.1.0
- Spring Boot 3.5.0

**Same error:**
```
org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
org/apache/maven/surefire/report/RunModeSetter
```

**Working solution:**
I found a workaround by adding an exclusion to the jDSP dependency in my `pom.xml`:

```xml
<dependency>
    <groupId>com.github.psambit9791</groupId>
    <artifactId>jdsp</artifactId>
    <version>3.1.0</version>
    <exclusions>
        <exclusion>
            <groupId>org.junit.platform</groupId>
            <artifactId>junit-platform-surefire-provider</artifactId>
        </exclusion>
    </exclusions>
</dependency>
```

After adding this exclusion, `mvn test` works perfectly.

**Context:**
This appears to be related to [[SUREFIRE-2285](https://issues.apache.org/jira/browse/SUREFIRE-2285)](https://issues.apache.org/jira/browse/SUREFIRE-2285), where jDSP is specifically mentioned as causing this `RunModeSetter` ClassNotFoundException. The issue seems to affect multiple Java versions (your Java 17, my Java 24) and multiple jDSP versions.

Hope this helps as a temporary workaround while a permanent fix is developed!
